name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Run Containers
    runs-on: ubuntu-latest
    steps:        
    - name: Checkout
      uses: actions/checkout@v4


    - name: Checkout backend repo
      uses: actions/checkout@v4
      with:
        repository: portal_infrastructure/backend
        path: backend

    - name: Checkout web repo
      uses: actions/checkout@v4
      with:
        repository: portal_infrastructure/web
        path: web
        
    - name: Start containers
      run: docker-compose -f "docker/docker-compose.yml" up -d --build

