name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Run Containers
    runs-on: ubuntu-latest
    steps:        
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Docker image frontend
      uses: docker/build-push-action@v5
      with:
        context: ./web/
        tags: teamtells/frontend:latest
        labels: deploy

    - name: Build Docker image backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend/
        tags: teamtells/backend:latest
        labels: deploy

